[server]
app_name="go-modular"
mode = "info"
port = "8080"
http_timeout = 60
cache_expired = 24
cache_purged = 60
api_version = "1"

[database]
db_driver = "mysql"
db_host = "db"
db_port = "3307"
db_name = "backend_modules"
db_username = "terarush"
db_password = "perdafosteam"

[pool]
conn_idle = 200
conn_max = 300
conn_lifetime = 60

[jwt]
day_expired = 60
signature_key = "4WSRLWxJdm"
